# Generated by Django 6.0 on 2025-12-16 00:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_alter_address_latitude_alter_address_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('group', models.BooleanField(default=False, verbose_name='grupo')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name': 'conversa',
                'verbose_name_plural': 'conversas',
                'db_table': 'thread',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='profiles.profile', verbose_name='remetente')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.thread', verbose_name='conversa')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'db_table': 'message',
                'indexes': [models.Index(fields=['thread', '-created_at'], name='message_thread__cc928c_idx'), models.Index(fields=['sender', '-created_at'], name='message_sender__adf9a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThreadParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='última leitura em')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='profiles.profile', verbose_name='perfil')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.thread', verbose_name='conversa')),
            ],
            options={
                'verbose_name': 'participante da conversa',
                'verbose_name_plural': 'participantes da conversa',
                'db_table': 'thread_participant',
                'indexes': [models.Index(fields=['thread', 'profile'], name='thread_part_thread__378059_idx')],
                'constraints': [models.UniqueConstraint(fields=('thread', 'profile'), name='unique_thread_profile')],
            },
        ),
    ]
