# Generated by Django 6.0 on 2025-12-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deletado em'),
        ),
        migrations.AddField(
            model_name='thread',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deletado em'),
        ),
        migrations.AddField(
            model_name='threadparticipant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deletado em'),
        ),
    ]
