# Generated by Django 6.0 on 2025-12-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_deleted_at_thread_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='title',
        ),
    ]
