# Generated by Django 6.0 on 2025-12-12 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deletado em')),
                ('type', models.CharField(choices=[('client', 'Cliente'), ('instructor', 'Instrutor')], max_length=10, verbose_name='tipo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='cpf')),
                ('phone', models.CharField(max_length=13, unique=True, verbose_name='telefone')),
                ('birthdate', models.DateField(verbose_name='data de nascimento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deletado em')),
                ('zip_code', models.CharField(db_index=True, max_length=20, verbose_name='cep')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='logradouro')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='número')),
                ('neighborhood', models.CharField(blank=True, max_length=255, null=True, verbose_name='bairro')),
                ('complement', models.TextField(blank=True, max_length=255, null=True, verbose_name='complemento')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='estado')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='região')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='país')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='profiles.profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
                'db_table': 'address',
            },
        ),
    ]
