# Generated by Django 6.0 on 2025-12-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='complemento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('client', 'Cliente'), ('instructor', 'Instrutor')], max_length=10, verbose_name='tipo'),
        ),
    ]
